apiVersion: v1
kind: Config
users:
- name: admin-user
  user:
    token: XXXXXXXXX
clusters:
- cluster:
    certificate-authority-data: YYYYYYYYYYYYYY
    server: https://<k8s-api-server-address>:6443
  name: self-hosted-cluster
contexts:
- context:
    cluster: kubernetes
    user: admin-user
  name: admin-context
current-context: admin-context
